{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MEDIA_SOURCE"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcstatstype\/media_source"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcstatstype\/media_source"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/MEDIA_SOURCE","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MEDIA_SOURCE"}],"title":"MCStatsType.MEDIA_SOURCE","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MCStatsType@MC_MEDIA_SOURCE","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MC_MEDIA_SOURCE"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/MEDIA_SOURCE":{"role":"symbol","title":"MCStatsType.MEDIA_SOURCE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MEDIA_SOURCE"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/MEDIA_SOURCE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MC_MEDIA_SOURCE"}],"url":"\/documentation\/millicastsdk\/mcstatstype\/media_source"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"role":"symbol","title":"MCStatsType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStatsType"}],"abstract":[{"type":"text","text":"Different types of statistics."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}],"url":"\/documentation\/millicastsdk\/mcstatstype"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MC_MEDIA_SOURCE"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MC_MEDIA_SOURCE"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MC_MEDIA_SOURCE"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1MEDIA_SOURCE\/title","value":"MC_MEDIA_SOURCE"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1MEDIA_SOURCE\/fragments","value":[{"kind":"identifier","text":"MC_MEDIA_SOURCE"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title","value":"MCStatsType"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","value":[{"kind":"identifier","text":"MCStatsType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}