{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"REMOTE_INBOUND_RTP"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcstatstype\/remote_inbound_rtp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcstatstype\/remote_inbound_rtp"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/REMOTE_INBOUND_RTP","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"REMOTE_INBOUND_RTP"}],"title":"MCStatsType.REMOTE_INBOUND_RTP","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MCStatsType@MC_REMOTE_INBOUND_RTP","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MC_REMOTE_INBOUND_RTP"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"role":"symbol","title":"MCStatsType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStatsType"}],"abstract":[{"type":"text","text":"Different types of statistics."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}],"url":"\/documentation\/millicastsdk\/mcstatstype"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/REMOTE_INBOUND_RTP":{"role":"symbol","title":"MCStatsType.REMOTE_INBOUND_RTP","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"REMOTE_INBOUND_RTP"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/REMOTE_INBOUND_RTP","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MC_REMOTE_INBOUND_RTP"}],"url":"\/documentation\/millicastsdk\/mcstatstype\/remote_inbound_rtp"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MC_REMOTE_INBOUND_RTP"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MC_REMOTE_INBOUND_RTP"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MC_REMOTE_INBOUND_RTP"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title","value":"MCStatsType"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","value":[{"kind":"identifier","text":"MCStatsType"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1REMOTE_INBOUND_RTP\/title","value":"MC_REMOTE_INBOUND_RTP"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1REMOTE_INBOUND_RTP\/fragments","value":[{"kind":"identifier","text":"MC_REMOTE_INBOUND_RTP"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}