{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mchttpconnectionerror\/reason-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mchttpconnectionerror\/reason-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHttpConnectionError\/reason-swift.property","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The HTTP error reason."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"reason","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MCHttpConnectionError(py)reason","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"reason"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHttpConnectionError"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCHttpConnectionError":{"role":"symbol","title":"MCHttpConnectionError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCHttpConnectionError"}],"abstract":[{"type":"text","text":"Container class for HTTP errors that occur during"},{"type":"text","text":" "},{"type":"text","text":"connection to the millicast service"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHttpConnectionError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCHttpConnectionError"}],"url":"\/documentation\/millicastsdk\/mchttpconnectionerror"},"doc://MillicastSDK/documentation/MillicastSDK/MCHttpConnectionError/reason-swift.property":{"role":"symbol","title":"reason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The HTTP error reason."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHttpConnectionError\/reason-swift.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reason"}],"url":"\/documentation\/millicastsdk\/mchttpconnectionerror\/reason-swift.property"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"reason"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"reason"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"reason"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHttpConnectionError\/title","value":"MCHttpConnectionError"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHttpConnectionError\/fragments","value":[{"kind":"identifier","text":"MCHttpConnectionError"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHttpConnectionError~1reason-swift.property\/title","value":"reason"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHttpConnectionError~1reason-swift.property\/fragments","value":[{"kind":"identifier","text":"reason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}