{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UNKNOWN"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideotype\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcvideotype\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType\/UNKNOWN","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UNKNOWN"}],"title":"MCVideoType.UNKNOWN","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MCVideoType@MC_UNKNOWN","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MC_UNKNOWN"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCVideoType":{"role":"symbol","title":"MCVideoType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoType"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoType"}],"url":"\/documentation\/millicastsdk\/mcvideotype"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoType/UNKNOWN":{"role":"symbol","title":"MCVideoType.UNKNOWN","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UNKNOWN"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType\/UNKNOWN","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MC_UNKNOWN"}],"url":"\/documentation\/millicastsdk\/mcvideotype\/unknown"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MC_UNKNOWN"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MC_UNKNOWN"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MC_UNKNOWN"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType\/title","value":"MCVideoType"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType\/fragments","value":[{"kind":"identifier","text":"MCVideoType"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType~1UNKNOWN\/title","value":"MC_UNKNOWN"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType~1UNKNOWN\/fragments","value":[{"kind":"identifier","text":"MC_UNKNOWN"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}